version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: user_generate_backend
    restart: always
    ports:
      - 3333:3333
    volumes:
      - ./backend:/app

  app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: user_generate_frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
    stdin_open: true
    links:
      - api
    depends_on:
      - api
