version: "3.9"

services:
  api:
    build: ./backend
    container_name: generate_user_backend
    restart: always
    ports:
      - 3333:3333
    volumes:
      - .:/backend/usr/api

  app:
    build: ./frontend
    container_name: generate_user_frontend
    restart: always
    ports:
      - 3000:3000
    volumes:
      - .:/frontend/usr/app
    links:
      - api
    depends_on:
      - api
